// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOguCePCcX9q_Gjp3Jq2vydRLaLVqlrBI',
    appId: '1:764642981880:android:cfc5a4ad73722f30e7480d',
    messagingSenderId: '764642981880',
    projectId: 'voice-clone-api',
    databaseURL:
        'https://voice-clone-api-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-clone-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLwdCsr07X2JBdC5ldbXd0_KMBWtMHpRc',
    appId: '1:764642981880:ios:91d7542bd6c167d2e7480d',
    messagingSenderId: '764642981880',
    projectId: 'voice-clone-api',
    databaseURL:
        'https://voice-clone-api-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voice-clone-api.appspot.com',
    iosClientId:
        '764642981880-6on78hmola8d4drjg63j6ng6nle2alkr.apps.googleusercontent.com',
    iosBundleId: 'project.bvritece.clonetalk',
  );
}
